[package]
name = "rbcx"
version = "0.1.0"
authors = ["James Nash <jrnash.dev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
clap = "4.3.19"
zip-extract = "0.1.2"
